[tasks.update]
description = "Update flake & apt"
run = [
    'sudo apt update && sudo apt upgrade -y',
    'nix flake update --flake .',
    """
    if ! jj st | rg "The working copy has no changes." >/dev/null; then \
      if jj log -r ~immutable\\(\\)\\&@- | rg "Update flake" >/dev/null; then \
        jj squash; \
      else \
        jj commit -m "Update flake" && jj tug; \
      fi; \
    fi \
    """,
    'home-manager switch --flake .',
    'SYS_RESULT_DIR=$(nix run "github:numtide/system-manager" -- build --flake .); sudo "${SYS_RESULT_DIR}//bin/activate"',
]
