{...}: {
  flake.modules.homeManager.carl-packages = {
    config,
    lib,
    pkgs,
    pkgs-unstable,
    pkgs-oldstable,
    ...
  }: {
    home.packages =
      (with pkgs; [
        lazyjj
        jjui
        jj-fzf
        btop
        dia
        gimp
        inkscape
        kdePackages.kdenlive
        lyx
        broot
        pay-respects
        oils-for-unix
        minicom
        fzf
        b3sum
        black
        shellcheck
        tree
        binutils
        unzip
        fd
        ripgrep
        obs-studio
        vlc
        nix-index
        any-nix-shell
        zsh
        zsh-z
        zsh-fzf-tab
        zsh-autocomplete
        zsh-you-should-use
        zsh-autosuggestions
        zsh-syntax-highlighting
        nix-zsh-completions
        cod
        jq
        orpie
        bitwise
        strace
        eza
        rustup
        dhex
        lnav
        usbutils
        nixpkgs-fmt
        wl-clipboard
        dmidecode
        zotero
        fastgron
        mermaid-cli
        graphviz
        plantuml
        vimPlugins.which-key-nvim
        distrobox
        android-tools
        just
        ruff
        ty
        unixtools.xxd
        protobuf
        lsof
        gh
        systemctl-tui
        atuin
        qalculate-qt
        alejandra
        nixfmt-tree
        clang-tools
        kdePackages.okular
        k9s
        gcc
        iosevka
        scrcpy
        freecad
        difftastic
        watchman
        typst
        typstyle
        okteta
        age
        pre-commit
        prek
        ghidra
        mergiraf
        nix-output-monitor
        jdk25_headless
        kicad
        nixd
      ])
      ++ (with pkgs;
        lib.optionals config.personal.packages [
          kdePackages.kate
          direnv
          steam
          steam-run
          davinci-resolve
        ])
      ++ (with pkgs-unstable; [
        uv
        mise
        zed-editor
      ])
      ++ (with pkgs-oldstable; [
      ]);
  };
}
